koinos/koinos-p2p

- ci/install.sh
- cmd/koinos-p2p/main.go
- go.mod
- go.sum
- internal/node/node.go
- internal/node/node_test.go
- internal/options/blacklist_options.go
- internal/options/config.go
- internal/options/download_manager_options.go
- internal/options/download_provider_options.go
- internal/options/node_options.go
- internal/options/peer_handler_options.go
- internal/options/sync_manager_options.go
- internal/options/sync_service_options.go
- internal/p2p_test.go
- internal/protocol/blacklist.go
- internal/protocol/download_manager.go
- internal/protocol/download_provider.go
- internal/protocol/gossip.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
- internal/protocol/sync_service.go
- internal/protocol/topology_cache.go
- internal/rpc/koinos_rpc.go
- internal/rpc/rpc.go
- internal/util/comparable.go
- internal/util/types.go
Merge for the `big-p2p-refactor` branch.  All unit tests passing.  
Blocked by: 
koinos/koinos-mq-golang#11
koinos/koinos-mq-golang#12
> Big p2p refactor

- internal/protocol/download_manager.go
- internal/protocol/download_provider.go
- internal/protocol/gossip.go
- internal/protocol/peer_handler.go
- internal/util/helpers.go
Depends on PR #80.  Merge #80 first.
Closes #67.
> Improve logging

- internal/protocol/gossip.go
> Check for self-published messages in gossip

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/protocol/download_manager.go
- internal/protocol/download_provider.go
- internal/protocol/gossip.go
- internal/protocol/notify.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
- internal/protocol/sync_service.go
- internal/protocol/topology_cache.go
- internal/rpc/koinos_rpc.go
- internal/util/helpers.go
Fixes log formatting, and some log levels
> Properly use format logs

- cmd/koinos-p2p/main.go
> Respect instance id and log level from yaml config

- cmd/koinos-p2p/main.go
> Fix AMQP default URL

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/node/peer_reconnect.go
- internal/p2p_test.go
- internal/protocol/notify.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
> Peer Reconnect

- ci/after_success.sh
- ci/build.sh
- ci/install.sh
- ci/test.sh
- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/node/peer_reconnect.go
- internal/p2p_test.go
- internal/protocol/notify.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
Should be reviewed/merged after #96
> Integration Tests

- internal/node/node.go
> Add warning messages when broadcast parsing fails

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/download_manager_options.go
- internal/options/node_options.go
- internal/p2p_test.go
- internal/protocol/download_manager.go
- internal/protocol/download_provider.go
- internal/protocol/gossip.go
- internal/protocol/gossip_voter.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
- internal/protocol/topology_cache.go
> Automatically transition to gossip

- internal/protocol/download_manager.go
- internal/protocol/download_provider.go
- internal/protocol/notify.go
- internal/protocol/peer_handler.go
- internal/protocol/sync_manager.go
- internal/protocol/topology_cache.go
> Peer cleanup

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/node_options.go
> Start gossip

- internal/protocol/topology_cache.go
> Implement topology cache SetLastIrr

- internal/protocol/download_provider.go
> Fix optional segv

- go.mod
- go.sum
- internal/protocol/download_manager.go
- internal/protocol/sync_service.go
- internal/protocol/topology_cache.go
> Threadsafe topology cache

- internal/protocol/download_provider.go
- internal/protocol/sync_manager.go
> Properly internally synchronize BdmiProvider

- go.mod
- go.sum
- internal/node/node.go
- internal/protocol/gossip.go
> Prevent gossip spam based on LIB

- internal/node/node.go
> Use sha256 for peer exchange also

- internal/p2p_test.go
> Fix blacklist test race condition

- internal/protocol/download_manager.go
> Clear downloads when peer disconnects

- internal/protocol/connection_manager.go
- internal/protocol/errors.go
- internal/protocol/gossip.go
> Ignore gossip for blacklist

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/config.go
- internal/options/gossip_toggle_options.go
- internal/p2p/connection_manager.go
- internal/p2p/gossip_toggle.go
- internal/p2p/gossip_toggle_test.go
- internal/p2p/peer_connection.go
Closes #164
Should be reviewed/merged after #167
> Gossip Threshold

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/config.go
- internal/options/error_handler_options.go
- internal/options/peer_connection_options.go
- internal/p2p/connection_manager.go
- internal/p2p/error_handler.go
- internal/p2p/peer_connection.go
- internal/p2p_test.go
- internal/p2perrors/errors.go
Closes #165
Should be reviewed and merged after #168
> Checkpoints

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/node_options.go
> Remove bootstrap option

- internal/node/node_test.go
- internal/p2p_test.go
> Lock TestRPC

- internal/node/node.go
> Fix peer id logging

- go.mod
- go.sum
- internal/rpc/koinos_rpc.go
> Bump proto

- go.mod
- go.sum
- internal/node/node.go
- internal/node/node_test.go
- internal/p2p/gossip_toggle.go
- internal/p2p/gossip_toggle_test.go
- internal/p2p_test.go
- internal/rpc/koinos_rpc.go
- internal/rpc/local_rpc.go
> Broadcast gossip

- internal/p2p/peer_connection.go
> Do not give naughty points on local block application timeout

- internal/p2p/gossip.go
> Fix bad log message

- go.mod
- go.sum
- internal/node/node.go
- internal/node/node_test.go
- internal/options/block_applicator_options.go
- internal/options/config.go
- internal/options/error_handler_options.go
- internal/p2p/block_applicator.go
- internal/p2p/block_applicator_test.go
- internal/p2p/error_handler.go
- internal/p2p/gossip.go
- internal/p2p/peer_connection.go
- internal/p2perrors/errors.go
- internal/rpc/koinos_rpc.go
Adds an additional layer between gossip and block application that orders blocks.
> Block applicator

- cmd/koinos-p2p/main.go
- go.mod
- go.sum
- internal/p2p/block_applicator.go
- internal/p2p/gossip_toggle.go
- internal/p2p/peer_connection.go
- internal/p2p_test.go
Resolves #224
- Fixes gossip flags
- Waits on Client and Request Handler to connect before starting
- Correctly return errors during sync
> Fix bucket brigade failures

- go.mod
- go.sum
- internal/rpc/koinos_rpc.go
Resolves #222
Handle a case where p2p submits a block that is prior to the LIB from the chain perspective.
> Better LIB handling

- internal/node/node.go
- internal/options/error_handler_options.go
- internal/p2p/connection_manager.go
- internal/p2p/error_handler.go
- internal/p2p/error_handler_test.go
Resolves #220
Tracks error score by IP instead of peer ID
> 220 track IP for errors

- internal/p2p/applicator.go
Duplicate block applications would both get requested. This fixes the behavior to not have multiple application requests in flight at the same time.
> Maybe fix duplicate block applications ¯\_(ツ)_/¯

- internal/p2p/applicator.go
Track pending block applications to prevent duplicate request applications
> Track pending block applications to prevent duplicate request applications

- internal/node/node.go
- internal/p2p/gossip.go
- internal/p2p/gossip_toggle.go
- internal/p2p/gossip_toggle_test.go
Resolves 
Broadcast gossip off when disconnected from peers
> Also broadcast gossip off when disconnected from peers

- internal/node/node.go
Resolves 
Maybe fix a panic on node shutdown during testing
> Possibly fix panic observed during testing

- internal/node/node.go
- internal/p2p/applicator.go
- internal/p2p/applicator_test.go
- internal/p2p/gossip.go
- internal/p2perrors/errors.go
Resolves #252 
Move the transaction cache to the block applicator layer
> Move transaction cache to the applicator layer

- internal/options/error_handler_options.go
Reduce transaction application error score
> Reduce transaction application error score to 100

- internal/node/node.go
- internal/options/gossip_toggle_options.go
- internal/p2p/connection_manager.go
- internal/p2p/gossip.go
- internal/p2p/gossip_toggle.go
- internal/p2p/gossip_toggle_test.go
- internal/p2p/peer_connection.go
Resolves #253.
Toggle gossip on and off based on the head block time distance to current wall clock time. (1 minute)
> Wall clock gossip toggle

- internal/node/node.go
> Tweak pubsub settings

- internal/p2p/gossip.go
Resolves 
```
2022-10-21 10:25:35.587715 (p2p.Koinos) [p2p/gossip.go:219] <info>: Recently gossiped 25 block(s) and 2 transaction(s)
2022-10-21 10:26:33.590817 (p2p.Koinos) [node/node.go:368] <info>: My address:
2022-10-21 10:26:33.591735 (p2p.Koinos) [node/node.go:369] <info>:  - /ip4/10.0.0.57/tcp/8888/p2p/QmejjrcPCpi74K4pdGA7GBnDdDkqTF4jVDeGYDj7mJPgfv
2022-10-21 10:26:33.591762 (p2p.Koinos) [node/node.go:370] <info>: Connected peers:
2022-10-21 10:26:33.591786 (p2p.Koinos) [node/node.go:372] <info>:  - /ip4/139.144.17.121/tcp/8888/p2p/QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
2022-10-21 10:26:33.591805 (p2p.Koinos) [node/node.go:372] <info>:  - /ip4/144.91.72.52/tcp/8888/p2p/QmWsEFV7aCz9DuFU4mEXo3gQwiVFH1NK31X28Fi2VyPJnG
2022-10-21 10:26:33.591822 (p2p.Koinos) [node/node.go:372] …
```
> Calm down the gossip logging

- internal/node/node.go
- internal/p2p/connection_manager.go
- internal/p2p/gossip_toggle.go
- internal/p2p/gossip_toggle_test.go
When we disconnect from everyone, we should toggle gossip off.
> Toggle gossip off if we disconnect from everyone

- internal/p2p/gossip.go
The go routine that logs gossip summaries does not exit when gossip is toggled off, but a new one is created every time Gossip is toggled back on. This PR cancels the go routine when gossip is toggled off so that only one copy of the routine is running at a time.
> Correctly clean up gossip tracking goroutine when gossip is disabled

- internal/p2p/applicator.go
- internal/p2p/gossip_toggle.go
- internal/p2perrors/errors.go
- internal/rpc/koinos_rpc.go
Add some more fixes to increase applicator stability and increase gossip toggle delta to 45s
> Gossip Stability

- internal/node/node.go
- internal/options/error_handler_options.go
Proposal of modifications to P2P settings to improve network cohesion for those with poor internet connections.
> P2P settings changes

- internal/options/peer_connection_options.go
- internal/rpc/koinos_rpc.go
Limit block batches to 500 and check message size.
> Limit block batches to 500 and check message size

- Dockerfile
- ci/build.sh
- cmd/koinos-p2p/main.go
```
$ ~/src/koinos-p2p$ ./koinos-p2p -v
Koinos P2P v1.0.0 (3a947571)
$ ~/src/koinos-p2p$ ./koinos-p2p --version
Koinos P2P v1.0.0 (3a947571)
$ ~/src/koinos-p2p$ ./koinos-p2p
2022-11-03 17:16:01.266051 (p2p.Koinos) [koinos-p2p/main.go:131] <info>: Koinos P2P v1.0.0 (3a947571)
```
> Bump version numbers

- cmd/koinos-p2p/main.go
- go.mod
- go.sum
Resolves koinos/koinos-internal#196.
Upgrade the log library.
> Normalize logs

- go.mod
- go.sum
> Bump proto to v2.0.2 and util to v2.0.1

- .travis.yml
> Remove docker repo from apt

- cmd/koinos-p2p/main.go
Bumps microservice to version v1.2.0.
> Bump version to v1.2.0

- .travis.yml
- internal/p2p/gossip.go
> Fix linting

- Dockerfile
- go.mod
- internal/p2p/applicator.go
- internal/p2p/applicator_test.go
- internal/p2p/gossip.go
Resolves #316 
Resets the applicator when gossip is toggled off.
> 316: Reset Applicator

- go.mod
- go.sum
- internal/p2p/applicator.go
- internal/p2perrors/errors.go
- internal/rpc/koinos_rpc.go
Resolves #320
Handles pending transaction limit errors to better ensure successful application of transactions.
> Handle pending trx limit
