- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/node/node_test.go
- internal/p2p_test.go
- internal/protocol/peer_handler.go
It now will properly produce the same ID given the same key. 
Some cleanup was also done; 
- If generating a random seed, it will log that seed so it can be reused by the node operator.
- Seeds are now uint64 to avoid weird negative seeds
Resolves #66
> Fix peer ID generation

- internal/p2p/peer_connection.go
- internal/p2p_test.go
This adds a check in the sync code that if the peer's head block is known in the block cache, don't request any blocks. This cuts down on spammy requests and duplicate block application.
```
./build/koinos_p2p -a amqp://guest:guest@localhost:5672/
2022-03-18 14:02:18.589520 (p2p.Koinos) [koinos-p2p/main.go:139] <info>: Attempting to connect to block_store...
2022-03-18 14:02:18.590018 (p2p.Koinos) [koinos-mq-golang@v0.0.0-20220307194511-07a03f6f75f0/client.go:95] <info>: Connecting client to AMQP server amqp://guest:guest@localhost:5672/
2022-03-18 14:02:18.591617 (p2p.Koinos) [koinos-mq-golang@v0.0.0-20220307194511-07a03f6f75f0/connection.go:85] <info>: Dialing AMQP server amqp://guest:guest@localhost:5672/
2022-03-18 14:02:18.592964 (p2p.Koinos) …
```
> Slow duplicate requests

- internal/node/node.go
- internal/options/block_applicator_options.go
- internal/options/peer_connection_options.go
- internal/p2p/block_applicator.go
- internal/p2p/connection_manager.go
- internal/p2p/peer_connection.go
- internal/p2p_test.go
Resolves #205 
Resolves #217
Connects peer connection to the block applicator to prevent out of order, duplicate, and irreversible block application. This significantly reduces error messages and increases peer connection stability during sync.
```
2022-08-25 10:28:02.982769 (p2p.Koinos) [p2p/peer_connection.go:144] <info>: Requesting blocks 1879-2879 from peer QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
2022-08-25 10:28:02.996044 (p2p.Koinos) [p2p/peer_connection.go:144] <info>: Requesting blocks 1879-2879 from peer QmbU6XyuGNiWk613bxqGdiGki11nZxa7weoBAdBp9cQoxB
2022-08-25 10:28:03.279048 (p2p.Koinos) [p2p/peer_connection.go:144] <info>: Requesting blocks 1879-2879 from peer QmbgUbBpYpG56deCGBXZfga1XzrHyZe8LMHBGQKKtFxx3E
2022-08-25 10:28:03.799799 (p2p.Koinos) …
```
> Optimize sync

- internal/options/error_handler_options.go
- internal/p2p/block_applicator.go
- internal/p2p/block_applicator_test.go
- internal/p2p/fork_watchdog.go
- internal/p2p/fork_watchdog_test.go
- internal/p2p/peer_connection.go
- internal/p2perrors/errors.go
Resolves #221.
Detect and handle for bombs. When a user creates more than 3 blocks off the same parent we consider that a fork bomb and spank you off the network.
```console
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestForkWatchdog$ github.com/koinos/koinos-p2p/internal/p2p
ok  	github.com/koinos/koinos-p2p/internal/p2p	0.172s
```
> Detect and handle fork bombs

- internal/options/block_applicator_options.go
- internal/p2p/block_applicator.go
- internal/p2p/block_applicator_test.go
- internal/p2p/peer_connection.go
Resolves #230
If a block is too far in the future, delay its application by a little bit, erroring if it is further in the future than the timeout allows for.
```
$ go test ./...
?       github.com/koinos/koinos-p2p/cmd/koinos-p2p     [no test files]
ok      github.com/koinos/koinos-p2p/internal   (cached)
ok      github.com/koinos/koinos-p2p/internal/node      (cached)
?       github.com/koinos/koinos-p2p/internal/options   [no test files]
ok      github.com/koinos/koinos-p2p/internal/p2p       (cached)
?       github.com/koinos/koinos-p2p/internal/p2perrors [no test files]
?       github.com/koinos/koinos-p2p/internal/rpc       [no test files]
```
> Delay blocks that are too far in the future

- internal/p2p/block_applicator.go
Make the error channel a buffered channel so that if the block application times out, the calling go routine does not get blocked.
> Make the applicator error channel bufferred

- internal/node/node.go
- internal/options/applicator_options.go
- internal/options/config.go
- internal/options/peer_connection_options.go
- internal/p2p/applicator.go
- internal/p2p/applicator_test.go
- internal/p2p/connection_manager.go
- internal/p2p/gossip.go
- internal/p2p/peer_connection.go
- internal/p2p_test.go
Resolves #229
Renames `BlockApplicator` to `Applicator` and now also handles transaction application. The Applicator class prioritizes block application over transaction application.
> Prioritize Block Application

- internal/p2p/block_applicator.go
Resolves #233
Cleanup the LIB processing to a) be more efficient and b) be more complete in cleaning up old requests
> Cleanup LIB processing in block applicator

- go.mod
- internal/node/node.go
mr-tron base58 encoding was stopping block broadcasts from being handled for large blocks.
```
2022-09-20 16:44:59.527124 (p2p.Koinos) [p2p/connection_manager.go:252] <info>: Attempting to connect to peer QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
2022-09-20 16:44:59.872184 (p2p.Koinos) [p2p/connection_manager.go:166] <info>: Connected to peer: /ip4/139.144.17.121/tcp/8888/p2p/QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
2022-09-20 16:45:00.354386 (p2p.Koinos) [p2p/peer_connection.go:144] <info>: Requesting blocks 12138-13138 from peer QmcGiTpSm6YrmYo3rWoqrCPez2aJY4VdraBQsGsZKwFRuG
2022-09-20 16:45:00.366585 (p2p.Koinos) [p2p/connection_manager.go:166] <info>: Connected to peer: /ip4/45.79.175.16/tcp/8888/p2p/QmeQWPqQndKMe2nb7gxHBkycJaFCiBsyjJS9sPdTEgh59M
2022-09-20 16:45:00.694995 …
```
> Base58 sync fix

- internal/p2p/peer_connection.go
Restores sync check that was erroneously removed
> Restore check for peer de-sync

- internal/options/peer_connection_options.go
increases the batch block request timeout to 5m for 1000 batch with maximum block size.
> Increase the batch block request timeout

- internal/options/error_handler_options.go
- internal/p2p/error_handler.go
- internal/p2p/error_handler_test.go
Resolves #243.
An error score must decay to half the disconnect threshold before a reconnection attempt is made.
```console
=== RUN   TestErrorHandler
--- PASS: TestErrorHandler (3.50s)
```
> Error score reconnect threshold

- internal/options/error_handler_options.go
- internal/p2p/applicator.go
- internal/p2p/applicator_test.go
- internal/p2p/error_handler.go
- internal/p2perrors/errors.go
With the PoB Node Comparator, it is possible that the head block is not the highest block. If that happens and one of the blocks higher than head is built on, the block will get stuck in the applicator. This change allows that block to be applied and progress to be made.
> Track highest block height instead of just head

- internal/p2p/gossip.go
Possibly resolves #238
Do not change the subscription pointer out from under `readMessages`.
> Store subscription locally to avoid nil pointer dereference

- internal/p2p/gossip.go
Removes 10 seconds timeout from transactions added to the applicator.
> Removes the 10 seconds timeout when adding a txs to the applicator

- internal/p2p/connection_manager.go
Resolves #278 
Refactor the seed connection loop to prevent attempting to connect to an already connected seed.
The only seeds the node is attempting to connect to are seeds that are down.
```
2024-06-14 12:38:52.350509 (p2p.YLJbz) [node/node.go:375] <info>: My address:
2024-06-14 12:38:52.350701 (p2p.YLJbz) [node/node.go:376] <info>:  - /ip4/127.0.0.1/tcp/8888/p2p/QmR6rdTe14uczcj8CRBk4jc7NHKHPXWxkDiPAompitGuzu
2024-06-14 12:38:52.350715 (p2p.YLJbz) [node/node.go:377] <info>: Connected peers:
2024-06-14 12:38:52.350746 (p2p.YLJbz) [node/node.go:379] <info>:  - /ip4/95.216.68.185/tcp/8888/p2p/QmQzxW8XimrSyFDeNpd87WnwB54vVMR9tbiPqzykLT6K7F
2024-06-14 12:38:52.350762 (p2p.YLJbz) [node/node.go:379] <info>:  - /ip4/95.216.2.248/tcp/8888/p2p/QmSt8SKKtsNWcBbx2WEZdiHKb4XGPZyVGK2bmgneFZyRcL …
```
> Connect to seeds refactor

- go.mod
- go.sum
- internal/node/node.go
- internal/options/config.go
- internal/options/connection_manager_options.go
- internal/options/error_handler_options.go
- internal/p2p/connection_manager.go
- internal/p2p/error_handler.go
- internal/p2p/peer_connection.go
- internal/p2p/protocol_version.go
- internal/p2p/protocol_version_provider.go
- internal/p2perrors/errors.go
Resolves #294
Reports a koinos protocol version `koinos/p2p/1.0.0` and disconnects from peers that have a different stated protocol.
```
2024-06-14 13:41:35.203181 (p2p.NVERf) [node/node.go:377] <info>: My address:
2024-06-14 13:41:35.203229 (p2p.NVERf) [node/node.go:378] <info>:  - /ip4/127.0.0.1/tcp/8888/p2p/QmVG6ZrGfxDQs6ai4Gnt8iAuVwvC4tFm2hRgoYdMw5nwWY
2024-06-14 13:41:35.203234 (p2p.NVERf) [node/node.go:379] <info>: Connected peers:
2024-06-14 13:41:35.203243 (p2p.NVERf) [node/node.go:381] <info>:  - /ip4/185.216.75.233/udp/4001/quic-v1/p2p/12D3KooWPeSVAgy4nX3rwaWaBqwkZuhGomECdJmmWQbL4BySAU12
2024-06-14 13:41:35.203250 (p2p.NVERf) [node/node.go:381] <info>:  - /ip4/159.138.104.117/udp/4001/quic-v1/p2p/12D3KooWGCuwGdtEK39z58miEbEFNKjUs3EPwRK1XgSqdjE6uqjX
2024-06-14 13:41:35.203256 …
```
> Protocol version

- cmd/koinos-p2p/main.go
- internal/node/node.go
- internal/options/node_options.go
Resolves #295.
Disables DHT routing with a flag, defaults to false. Needs testing. Do not merge.
> Add a flag to turn DHT local peer discovery, default the flag to false

- .travis.yml
- internal/p2p/applicator.go
Resolves #303
Renames the applicator instance to `a` and clarifies functions that operate on blocks (i.e. `addEntry` -> `addBlockEntry`).
> #303: Cleanup applicator

- internal/options/peer_connection_options.go
- internal/p2p/applicator.go
- internal/p2p/gossip.go
- internal/p2p/peer_connection.go
Resolves #304
Cleans up use of contexts to avoid leaking go routines when gossip is disabled or peers disconnect.
> Cleanup contexts

- internal/options/error_handler_options.go
- internal/p2p/applicator.go
- internal/p2p/applicator_test.go
- internal/p2p/error_handler.go
- internal/p2perrors/errors.go
Resolves #317
Sanitized blocks and transactions for required fields.
> 317: Sanitization
